/*******************************************************************************
 * CLI - A simple command line interface.
 * Copyright (C) 2016-2021 Daniele Pallastrelli
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

#ifndef CLI_DETAIL_FROMSTRING_H_
#define CLI_DETAIL_FROMSTRING_H_

// —— 本 fork 的偏离（上游此文件 283 行，这里只剩 std::string 一条支路）——
//
// 被删的是数值 / bool / char / 浮点 / operator>> 兜底这五类 from_string，连同
// bad_conversion。理由不是"用不到"，而是它们的**失败通道是异常**，而本 fork 的
// 整棵 include/ 树不使用异常（消费方以 /EHs-c- 或 -fno-exceptions 编译，头里的
// 裸 throw 在那种配置下是解析期硬错误，不是可选风格）。
//
// 主模板**声明而不定义**：注册一个非 std::string 参数的命令会在**链接期**失败。
// 这比"给个失败值"好——后者会让 `from_string<unsigned>("abc") -> 0` 这类东西
// 静默地把一条坏命令送进历史执行，而链接错误只会响亮地挡在编译门外。
//
// 需要数值参数的调用方自己解析（std::from_chars：无异常、失败有返回码）。

#include <string>

namespace cli
{
namespace detail
{

template <typename T>
inline T from_string(const std::string& s);

template <>
inline std::string from_string(const std::string& s)
{
    return s;
}

} // namespace detail
} // namespace cli

#endif // CLI_DETAIL_FROMSTRING_H_
