/*******************************************************************************
 * CLI - A simple command line interface.
 * Copyright (C) 2016-2021 Daniele Pallastrelli
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

#ifndef CLI_DETAIL_LINUXKEYBOARD_H_
#define CLI_DETAIL_LINUXKEYBOARD_H_

#include <cerrno>
#include <optional>
#include <thread>
#include <memory>

#include <cstdio>
#include <termios.h>
#include <unistd.h>
#include <sys/select.h>
#include <cassert>
#include <condition_variable>
#include "inputdevice.h"


namespace cli
{
namespace detail
{

class InputSource
{
public:

    InputSource()
    {
        int pipes[2];
        if (pipe(pipes) == 0)
        {
            shutdownPipe = pipes[1]; // we store the write end
            readPipe = pipes[0]; // ... and the read end
        }
    }

    // true = stdin 上有字符可读；false = Stop() 已生效，servant 线程该退出了。
    // 上游用 throw std::runtime_error("InputSource stop") 表达后者。
    //
    // 顺手修掉两处上游的问题（都是这一改造的必经之路，不是顺手清洁）：
    //   ① select 返回 -1（终端 resize 的 EINTR 等）时，上游掉出函数尾 —— 无返回值，UB；
    //   ② fd_set 只在循环外初始化一次，而 select 会改写它，第二轮的 FD_ISSET 读的是脏位。
    bool WaitKbHit()
    {
        for (;;)
        {
            fd_set rfds;
            FD_ZERO(&rfds);
            FD_SET(STDIN_FILENO, &rfds);
            FD_SET(readPipe, &rfds);

            const int ready = select(readPipe + 1, &rfds, nullptr, nullptr, nullptr);
            if (ready < 0)
            {
                if (errno == EINTR)
                    continue;
                assert(false);
                return false;
            }
            if (ready == 0)
                continue; // 无 timeout 时不该发生，保守重试

            if (FD_ISSET(readPipe, &rfds)) // stop called
            {
                close(readPipe);
                return false;
            }

            if (FD_ISSET(STDIN_FILENO, &rfds)) // char from stdinput
                return true;

            assert(false); // 不可达：ready > 0 必有其一被置位
            return false;
        }
    }

    void Stop()
    {
        auto unused = write(shutdownPipe, " ", 1);
        unused = close(shutdownPipe);
        static_cast<void>(unused); // silence unused warn
        shutdownPipe = -1;
    }

private:
    int shutdownPipe;
    int readPipe;
};

//

class LinuxKeyboard : public InputDevice
{
public:
    explicit LinuxKeyboard(Scheduler& _scheduler) :
        InputDevice(_scheduler),
        enabled(false),
        servant( [this]() noexcept { Read(); } )
    {
        ActivateInputImpl();
    }
    ~LinuxKeyboard() override
    {
        ToStandardMode();
        is.Stop();
        servant.join();
    }
    void ActivateInput() override
    {
        ActivateInputImpl();
    }
    void DeactivateInput() override
    {
        ToStandardMode();
        std::lock_guard<std::mutex> lock(mtx);
        enabled = false;
    }
    
    private:

    // we need a private non virtual method to call from the constructor
    void ActivateInputImpl()
    {
        ToManualMode();
        std::lock_guard<std::mutex> lock(mtx);
        enabled = true;
        cv.notify_one();
    }

    // 上游是 try{ while(true){...} }catch(const std::exception&){}，靠 WaitKbHit 抛出
    // 来退出 servant 线程。每轮的事件顺序保持原样：先等 enabled，再等键。
    void Read() noexcept
    {
        while (true)
        {
            {
                std::unique_lock<std::mutex> lock(mtx);
                cv.wait(lock, [this]{ return enabled; }); // release mtx, suspend thread execution until enabled becomes true
            }
            const auto k = Get();
            if (!k)
                return; // Stop() 已生效
            Notify(*k);
        }
    }

    char GetChar()
    {
        char buffer = 0;
        auto unused = read(0, &buffer, 1);
        static_cast<void>(unused); // silence unused warn
        return buffer;
    }

    // nullopt = 被 Stop() 打断（原 throw 的那一支）
    std::optional<std::pair<KeyType,char>> Get()
    {
        if (!is.WaitKbHit())
            return {};

        auto ch = GetChar();
        switch(ch)
        {
            case EOF:
            case 4:  // EOT
                return std::make_pair(KeyType::eof,' ');
                break;
            case 127:
            case 8:
                return std::make_pair(KeyType::backspace,' '); break;
            case 10: return std::make_pair(KeyType::ret,' '); break;
            case 12: return std::make_pair(KeyType::clear, ' '); break;
            case 27: // symbol
                ch = GetChar();
                if ( ch == 91 ) // arrow keys
                {
                    ch = GetChar();
                    switch( ch )
                    {
                        case 51:
                            ch = GetChar();
                            if ( ch == 126 ) return std::make_pair(KeyType::canc,' ');
                            else return std::make_pair(KeyType::ignored,' ');
                            break;
                        case 65: return std::make_pair(KeyType::up,' ');
                        case 66: return std::make_pair(KeyType::down,' ');
                        case 68: return std::make_pair(KeyType::left,' ');
                        case 67: return std::make_pair(KeyType::right,' ');
                        case 70: return std::make_pair(KeyType::end,' ');
                        case 72: return std::make_pair(KeyType::home,' ');
                        default: return std::make_pair(KeyType::ignored,' ');
                    }
                }
                break;
            default: // ascii
            {
                const char c = static_cast<char>(ch);
                return std::make_pair(KeyType::ascii,c);
            }
        }
        return std::make_pair(KeyType::ignored,' ');
    }

    void ToManualMode()
    {
        constexpr tcflag_t ICANON_FLAG = ICANON;
        constexpr tcflag_t ECHO_FLAG = ECHO;

        tcgetattr(STDIN_FILENO, &oldt);
        newt = oldt;
        newt.c_lflag &= ~( ICANON_FLAG | ECHO_FLAG );
        tcsetattr(STDIN_FILENO, TCSANOW, &newt);
    }

    void ToStandardMode()
    {
        tcsetattr(STDIN_FILENO, TCSANOW, &oldt);
    }

    bool enabled;
    termios oldt;
    termios newt;
    InputSource is;
    std::mutex mtx;
    std::condition_variable cv;
    std::thread servant;
};

} // namespace detail
} // namespace cli

#endif // CLI_DETAIL_LINUXKEYBOARD_H_


